/**
 * 车型知识库 — 硬编码典型数据
 * ===========================================
 * 修改说明：直接编辑本文件中的 carDatabase 数组即可新增/修改车型。
 * 每个字段含义参见 shared/schema.ts 中的 CarModel 接口。
 * 评分类字段统一使用 0-10 分制，保值率使用 0-1 小数。
 *
 * 车型总数：35 台
 * 覆盖品牌：理想、蔚来、小鹏、特斯拉、问界、阿维塔、比亚迪、腾势、
 *           极氪、小米、零跑、方程豹、深蓝、乐道、智己、智界、岚图
 * 最后更新：2026-03-19
 */

import type { CarModel } from "../shared/schema";

export const carDatabase: CarModel[] = [
  // ==================== 理想 ====================
  {
    id: "lixiang_l7",
    brand: "理想",
    model: "L7",
    priceRange: [31.98, 37.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "理想自研",
    seatComfort: 9,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 7,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.48,
    special: {
      erevAdvantage: "增程无续航焦虑，长途自驾无忧",
      futureBevPlan: true,
    },
    highlights: ["增程无焦虑", "家庭旗舰舒适", "冰箱彩电大沙发"],
    risks: ["纯电续航较短", "增程技术路线未来不确定性"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max/Pro",
    autoSummon: false,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 5,
    zeroto100: 5.3,

    // 车身尺寸
    bodyLength: 5050,
    bodyWidth: 1995,
    bodyHeight: 1750,
    wheelbase: 3005,

    // 牌照政策（增程）
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "lixiang_l8",
    brand: "理想",
    model: "L8",
    priceRange: [33.98, 39.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "理想自研",
    seatComfort: 9,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 9,
    brandPremium: 7,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.64,
    resaleRate5Year: 0.46,
    special: {
      erevAdvantage: "六座大空间，增程长途无焦虑",
      futureBevPlan: true,
    },
    highlights: ["六座大空间", "增程无焦虑", "家庭首选"],
    risks: ["价格偏高", "增程路线长期不确定"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max/Pro",
    autoSummon: false,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 5,
    zeroto100: 5.3,

    // 车身尺寸
    bodyLength: 5080,
    bodyWidth: 1995,
    bodyHeight: 1800,
    wheelbase: 3005,

    // 牌照政策（增程）
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "lixiang_l9",
    brand: "理想",
    model: "L9",
    priceRange: [42.98, 45.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 7,
    memoryParking: 8,
    infotainmentScore: 9,
    ecosystem: "理想自研",
    seatComfort: 10,
    soundInsulation: 9,
    suspensionScore: 9,
    rearSpace: 10,
    brandPremium: 8,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.83,
    resaleRate3Year: 0.66,
    resaleRate5Year: 0.49,
    special: {
      erevAdvantage: "旗舰全尺寸SUV，增程长途无焦虑",
      futureBevPlan: true,
    },
    highlights: ["全尺寸旗舰", "极致舒适", "智驾能力强"],
    risks: ["价格最高", "尺寸过大停车不便"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max",
    autoSummon: false,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 9,
    sportinessScore: 4,
    zeroto100: 5.3,

    // 车身尺寸
    bodyLength: 5218,
    bodyWidth: 1998,
    bodyHeight: 1800,
    wheelbase: 3105,

    // 牌照政策（增程）
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 蔚来 ====================
  {
    id: "nio_es6",
    brand: "蔚来",
    model: "ES6",
    priceRange: [33.80, 39.60],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: true,
    cltcRange: 625,
    realWorldRange: 490,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 8,
    highwayNoa: 7,
    cityNoa: 5,
    memoryParking: 6,
    infotainmentScore: 7,
    ecosystem: "蔚来自研",
    seatComfort: 8,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 8,
    serviceNetwork: 9,
    afterSalesScore: 9,
    resaleRate1Year: 0.78,
    resaleRate3Year: 0.58,
    resaleRate5Year: 0.40,
    special: {
      batteryRentalMonthly: [728, 1128],
      swapCoverage: 8,
    },
    highlights: ["换电3分钟满电", "车电分离降低购车成本", "服务体验行业标杆"],
    risks: ["纯电续航焦虑", "换电站覆盖三四线不足", "车电分离合同复杂"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsIncludedYears: 5,
    adsPlatform: "NAD",
    autoSummon: true,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "杜比全景声7.1.4",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 180,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 6,
    zeroto100: 4.5,

    // 车身尺寸
    bodyLength: 4854,
    bodyWidth: 1995,
    bodyHeight: 1703,
    wheelbase: 2915,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "nio_et5",
    brand: "蔚来",
    model: "ET5",
    priceRange: [29.80, 35.60],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: true,
    cltcRange: 560,
    realWorldRange: 430,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 8,
    highwayNoa: 7,
    cityNoa: 5,
    memoryParking: 6,
    infotainmentScore: 7,
    ecosystem: "蔚来自研",
    seatComfort: 7,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 6,
    brandPremium: 7,
    serviceNetwork: 9,
    afterSalesScore: 9,
    resaleRate1Year: 0.76,
    resaleRate3Year: 0.55,
    resaleRate5Year: 0.38,
    special: {
      batteryRentalMonthly: [728, 1128],
      swapCoverage: 8,
    },
    highlights: ["换电便捷", "运动轿车造型", "服务好"],
    risks: ["纯电续航一般", "后排空间不大", "保值率偏低"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsIncludedYears: 5,
    adsPlatform: "NAD",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "杜比全景声7.1.4",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 180,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 7,
    zeroto100: 4.0,

    // 车身尺寸
    bodyLength: 4790,
    bodyWidth: 1960,
    bodyHeight: 1499,
    wheelbase: 2888,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 小鹏 ====================
  {
    id: "xpeng_g6",
    brand: "小鹏",
    model: "G6",
    priceRange: [20.99, 27.69],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 580,
    realWorldRange: 450,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 9,
    cityNoa: 9,
    memoryParking: 8,
    infotainmentScore: 7,
    ecosystem: "小鹏自研(安卓)",
    seatComfort: 7,
    soundInsulation: 6,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 5,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.73,
    resaleRate3Year: 0.50,
    resaleRate5Year: 0.33,
    special: {},
    highlights: ["800V超充架构", "城市NOA行业领先", "性价比高"],
    risks: ["品牌溢价低保值率差", "做工细节一般", "服务网络偏弱"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "XNGP MAX",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 400,
    charge10to80min: 20,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 7,
    zeroto100: 3.9,

    // 车身尺寸
    bodyLength: 4753,
    bodyWidth: 1920,
    bodyHeight: 1650,
    wheelbase: 2890,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "xpeng_g9",
    brand: "小鹏",
    model: "G9",
    priceRange: [26.39, 35.99],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 650,
    realWorldRange: 510,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 9,
    cityNoa: 9,
    memoryParking: 8,
    infotainmentScore: 8,
    ecosystem: "小鹏自研(安卓)",
    seatComfort: 8,
    soundInsulation: 7,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 5,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.74,
    resaleRate3Year: 0.52,
    resaleRate5Year: 0.35,
    special: {},
    highlights: ["800V超充", "智驾旗舰", "空间表现好"],
    risks: ["保值率一般", "品牌力待提升", "售后覆盖不足"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "upfront",
    adsCostUpfront: 2.0,
    adsPlatform: "Ultra VLA",
    autoSummon: true,
    autoPark: 9,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 430,
    charge10to80min: 18,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 7,
    zeroto100: 3.9,

    // 车身尺寸
    bodyLength: 4891,
    bodyWidth: 1937,
    bodyHeight: 1670,
    wheelbase: 2998,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 特斯拉 ====================
  {
    id: "tesla_model3",
    brand: "特斯拉",
    model: "Model 3",
    priceRange: [23.19, 33.19],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 606,
    realWorldRange: 480,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 5,
    infotainmentScore: 7,
    ecosystem: "特斯拉封闭生态",
    seatComfort: 6,
    soundInsulation: 6,
    suspensionScore: 6,
    rearSpace: 6,
    brandPremium: 9,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.86,
    resaleRate3Year: 0.70,
    resaleRate5Year: 0.52,
    special: {},
    highlights: ["保值率行业第一", "超充网络成熟", "全球品牌影响力"],
    risks: ["内饰简陋", "舒适性一般", "智驾在国内受限"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "upfront",
    adsCostUpfront: 6.4,
    adsPlatform: "FSD V13",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: true,
    frunkVolume: 88,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "none",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "自研",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 250,
    charge10to80min: 25,
    hasHomeChargerIncluded: false,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 8,
    zeroto100: 3.1,

    // 车身尺寸
    bodyLength: 4720,
    bodyWidth: 1848,
    bodyHeight: 1442,
    wheelbase: 2875,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "tesla_modely",
    brand: "特斯拉",
    model: "Model Y",
    priceRange: [24.99, 35.49],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 554,
    realWorldRange: 430,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 5,
    infotainmentScore: 7,
    ecosystem: "特斯拉封闭生态",
    seatComfort: 6,
    soundInsulation: 6,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 9,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.87,
    resaleRate3Year: 0.72,
    resaleRate5Year: 0.54,
    special: {},
    highlights: ["保值率极高", "SUV实用性好", "超充覆盖广"],
    risks: ["内饰简陋", "舒适性不如同价位国产", "FSD在国内受限"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "upfront",
    adsCostUpfront: 6.4,
    adsPlatform: "FSD V13",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: true,
    frunkVolume: 117,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "none",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "自研",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 250,
    charge10to80min: 28,
    hasHomeChargerIncluded: false,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 7,
    zeroto100: 3.7,

    // 车身尺寸
    bodyLength: 4750,
    bodyWidth: 1921,
    bodyHeight: 1624,
    wheelbase: 2890,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 问界 ====================
  {
    id: "aito_m5",
    brand: "问界",
    model: "M5",
    priceRange: [24.98, 27.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1265,
    realWorldRange: 1050,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 8,
    memoryParking: 7,
    infotainmentScore: 9,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 7,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 7,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.80,
    resaleRate3Year: 0.62,
    resaleRate5Year: 0.44,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾ADS", "鸿蒙座舱体验一流", "增程无焦虑"],
    risks: ["底盘调校一般", "品牌认知仍在建设", "与华为绑定过深"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 Max",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "华为SOUND",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 100,
    charge10to80min: 40,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 5,
    zeroto100: 4.4,

    // 车身尺寸
    bodyLength: 4785,
    bodyWidth: 1930,
    bodyHeight: 1620,
    wheelbase: 2880,

    // 牌照政策（增程）
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "aito_m7",
    brand: "问界",
    model: "M7",
    priceRange: [24.98, 32.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1300,
    realWorldRange: 1080,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 8,
    memoryParking: 8,
    infotainmentScore: 9,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 8,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 9,
    brandPremium: 7,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.81,
    resaleRate3Year: 0.63,
    resaleRate5Year: 0.45,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾旗舰", "六座大空间", "鸿蒙座舱"],
    risks: ["底盘质感弱于理想", "品牌独立性存疑", "赛力斯品控口碑一般"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 Max",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "华为SOUND",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 100,
    charge10to80min: 40,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 5,
    zeroto100: 4.8,

    // 车身尺寸
    bodyLength: 5020,
    bodyWidth: 1945,
    bodyHeight: 1760,
    wheelbase: 2820,

    // 牌照政策（增程）
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 阿维塔 ====================
  {
    id: "avatr_11",
    brand: "阿维塔",
    model: "11",
    priceRange: [30.00, 39.00],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 600,
    realWorldRange: 470,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 7,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 8,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 7,
    brandPremium: 6,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.74,
    resaleRate3Year: 0.52,
    resaleRate5Year: 0.35,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾加持", "高端运动定位", "长安+华为+宁德联合"],
    risks: ["品牌知名度低", "保值率不确定", "服务网络待完善"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 (华为)",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 240,
    charge10to80min: 25,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 8,
    zeroto100: 3.98,

    // 车身尺寸
    bodyLength: 4880,
    bodyWidth: 1970,
    bodyHeight: 1601,
    wheelbase: 2975,

    // 牌照政策（纯电）
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 新增车型 — 2026-03-19 批量采集 ====================

  // ==================== 比亚迪 ====================
  {
    id: "byd_汉ev",
    brand: "比亚迪",
    model: "汉EV",
    priceRange: [17.98, 23.58],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 705,
    realWorldRange: 564,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7.5,
    cityNoa: 6.5,
    memoryParking: 7.0,
    infotainmentScore: 7.5,
    ecosystem: "自研",
    seatComfort: 7.5,
    soundInsulation: 7.5,
    suspensionScore: 7.5,
    rearSpace: 8.0,
    brandPremium: 7.0,
    serviceNetwork: 9.5,
    afterSalesScore: 8.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.52,
    special: {},
    highlights: ["800V高压平台，全系（除入门款）支持超快充，15-25分钟30%-80%", "旗舰版搭载激光雷达+DiPilot 300，城市NOA能力大幅提升", "丹拿音响标配，后排空间宽敞，综合豪华感强"],
    risks: ["入门款仍为400V平台，充电速度较慢", "自动驾驶能力相比华为ADS和小鹏有差距", "车机生态相对封闭，第三方应用支持有限"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "DiPilot 300 天神之眼C",
    autoSummon: false,
    autoPark: 7.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 150,
    charge10to80min: 25,
    hasHomeChargerIncluded: true,
    nvhScore: 7.5,
    sportinessScore: 7.0,
    zeroto100: 6.9,
    bodyLength: 4995,
    bodyWidth: 1910,
    bodyHeight: 1495,
    wheelbase: 2920,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "byd_宋l_ev",
    brand: "比亚迪",
    model: "宋L EV",
    priceRange: [18.98, 24.98],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 662,
    realWorldRange: 530,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 7.5,
    memoryParking: 7.0,
    infotainmentScore: 7.5,
    ecosystem: "自研",
    seatComfort: 7.5,
    soundInsulation: 7.5,
    suspensionScore: 7.5,
    rearSpace: 8.0,
    brandPremium: 6.5,
    serviceNetwork: 9.5,
    afterSalesScore: 8.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.64,
    resaleRate5Year: 0.5,
    special: {},
    highlights: ["猎装SUV造型出众，风阻系数低至0.255Cd，设计感在同级中领先", "无边框门+CTB电池车身一体化+云辇-C，操控与舒适兼顾", "前备厢（48L）+大后备厢，实用性突出"],
    risks: ["不支持800V超快充，补能速度落后于竞品", "城市NOA覆盖相对有限，高阶智驾需选配", "车高较低（1560mm），进出便利性略逊传统SUV"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "天神之眼C DiPilot 100",
    autoSummon: false,
    autoPark: 7.5,
    hasFrunk: true,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "front",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "丹拿",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 140,
    charge10to80min: 28,
    hasHomeChargerIncluded: true,
    nvhScore: 7.5,
    sportinessScore: 7.5,
    zeroto100: 6.9,
    bodyLength: 4840,
    bodyWidth: 1950,
    bodyHeight: 1560,
    wheelbase: 2930,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "byd_海豹",
    brand: "比亚迪",
    model: "海豹",
    priceRange: [17.58, 23.58],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 650,
    realWorldRange: 520,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 6.5,
    memoryParking: 6.5,
    infotainmentScore: 7.0,
    ecosystem: "自研",
    seatComfort: 7.0,
    soundInsulation: 7.0,
    suspensionScore: 8.0,
    rearSpace: 7.0,
    brandPremium: 6.5,
    serviceNetwork: 9.5,
    afterSalesScore: 8.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.64,
    resaleRate5Year: 0.51,
    special: {},
    highlights: ["800V高压平台，10%-80%仅需25分钟，快充能力在中型轿车中领先", "CTB电池车身一体化+五连杆后悬，操控与刚性出色", "四驱性能版0-100加速3.8秒，性价比极高"],
    risks: ["高配搭载激光雷达但城市NOA能力较弱，与特斯拉FSD差距明显", "车内储物空间偏少，无前备厢", "内饰用料在同价位竞品中偏平庸"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "DiPilot 100 天神之眼C",
    autoSummon: false,
    autoPark: 6.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: false,
    hasV2L: true,
    audioBrand: "比亚迪",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 150,
    charge10to80min: 25,
    hasHomeChargerIncluded: true,
    nvhScore: 7.5,
    sportinessScore: 8.5,
    zeroto100: 5.9,
    bodyLength: 4800,
    bodyWidth: 1875,
    bodyHeight: 1460,
    wheelbase: 2920,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "byd_唐ev",
    brand: "比亚迪",
    model: "唐EV",
    priceRange: [21.98, 26.98],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 730,
    realWorldRange: 584,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 6.5,
    memoryParking: 7.0,
    infotainmentScore: 7.5,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 7.5,
    suspensionScore: 7.0,
    rearSpace: 9.0,
    brandPremium: 7.0,
    serviceNetwork: 9.5,
    afterSalesScore: 8.5,
    resaleRate1Year: 0.78,
    resaleRate3Year: 0.62,
    resaleRate5Year: 0.48,
    special: {},
    highlights: ["7座SUV CLTC续航高达730km，家庭出行续航无忧", "108.8kWh刀片电池，安全性极高，三排空间宽敞舒适", "丹拿音响标配，豪华氛围浓厚，性价比突出"],
    risks: ["仍为400V平台，DC快充最高170kW，超快充能力不足", "体型较大（2820mm轴距），城市机动性受限", "2024款（非唐L），平台年龄较老，竞争力被唐L部分压制"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "天神之眼C DiPilot 100",
    autoSummon: false,
    autoPark: 7.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 170,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,
    nvhScore: 7.5,
    sportinessScore: 6.0,
    zeroto100: 7.9,
    bodyLength: 4900,
    bodyWidth: 1950,
    bodyHeight: 1725,
    wheelbase: 2820,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 腾势 ====================
  {
    id: "denza_n7",
    brand: "腾势",
    model: "N7",
    priceRange: [25.98, 28.98],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 702,
    realWorldRange: 562,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.5,
    cityNoa: 8.5,
    memoryParking: 8.5,
    infotainmentScore: 8.0,
    ecosystem: "自研",
    seatComfort: 9.0,
    soundInsulation: 8.5,
    suspensionScore: 9.0,
    rearSpace: 8.5,
    brandPremium: 7.5,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.78,
    resaleRate3Year: 0.6,
    resaleRate5Year: 0.46,
    special: {},
    highlights: ["全系标配双激光雷达+DiPilot 300，城市NOA全国可用，智驾水平领先同级", "800V+双枪超充（230kW），10%-80%仅20分钟，补能体验顶级", "云辇-A双腔空气悬架+帝瓦雷音响，舒适性达豪华SUV水准"],
    risks: ["腾势品牌溢价有限，二手保值率弱于BBA", "车机系统DiLink相比华为Harmony系统仍有差距", "车高偏低（1602mm），实际乘坐头部空间有压迫感"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "天神之眼B DiPilot 300",
    autoSummon: true,
    autoPark: 8.5,
    hasFrunk: true,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "帝瓦雷",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 230,
    charge10to80min: 20,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 7.5,
    zeroto100: 6.8,
    bodyLength: 4860,
    bodyWidth: 1935,
    bodyHeight: 1602,
    wheelbase: 2940,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "denza_d9_ev",
    brand: "腾势",
    model: "D9 EV",
    priceRange: [31.98, 46.98],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 620,
    realWorldRange: 496,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 8.0,
    memoryParking: 8.0,
    infotainmentScore: 8.5,
    ecosystem: "自研",
    seatComfort: 9.5,
    soundInsulation: 9.0,
    suspensionScore: 8.5,
    rearSpace: 9.5,
    brandPremium: 8.0,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.5,
    special: {},
    highlights: ["中国销量最高的新能源MPV，品牌认知度强，二手保值优于同级", "800V+双枪超充（200kW），MPV中补能速度领先，15分钟补能243km", "帝瓦雷音响+十屏互联+AirSPA零重力座椅，豪华商务氛围极佳"],
    risks: ["车身尺寸巨大（5250mm），城市停车困难", "纯电版续航620km中规中矩，不如增程版综合无忧", "竞品别克GL8 Flagship和极氪009压力较大"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "天神之眼C/B DiPilot",
    autoSummon: true,
    autoPark: 8.0,
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "帝瓦雷",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 200,
    charge10to80min: 22,
    hasHomeChargerIncluded: true,
    nvhScore: 9.0,
    sportinessScore: 5.5,
    zeroto100: 8.5,
    bodyLength: 5250,
    bodyWidth: 1960,
    bodyHeight: 1920,
    wheelbase: 3110,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 方程豹 ====================
  {
    id: "fangchengbao_豹5",
    brand: "方程豹",
    model: "豹5",
    priceRange: [26.98, 32.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1310,
    realWorldRange: 1114,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7.5,
    cityNoa: 7.5,
    memoryParking: 7.0,
    infotainmentScore: 7.5,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 7.0,
    suspensionScore: 8.5,
    rearSpace: 7.5,
    brandPremium: 6.5,
    serviceNetwork: 7.0,
    afterSalesScore: 7.0,
    resaleRate1Year: 0.75,
    resaleRate3Year: 0.58,
    resaleRate5Year: 0.44,
    special: {
      erevAdvantage: "增程无续航焦虑",
      huaweiSmartDriving: true,
    },
    highlights: ["DMO电驱越野平台，前后差速锁+云辇-P，真正的全地形硬派越野能力", "EREV综合续航高达1310km（CLTC），城市通勤+越野均无里程焦虑", "505kW/760Nm系统功率，4.8秒破百，兼顾性能与越野"],
    risks: ["方程豹品牌新，服务网络覆盖有限，维保便利性不足", "快充功率仅100kW，充电速度偏慢", "车重接近3吨，城市驾驶能耗较高"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "DiPilot / 华为乾崑ADS 4（高配）",
    autoSummon: false,
    autoPark: 7.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: false,
    hasV2L: true,
    audioBrand: "帝瓦雷",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 100,
    charge10to80min: 16,
    hasHomeChargerIncluded: true,
    nvhScore: 7.0,
    sportinessScore: 8.5,
    zeroto100: 4.8,
    bodyLength: 4890,
    bodyWidth: 1970,
    bodyHeight: 1920,
    wheelbase: 2800,
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 深蓝 ====================
  {
    id: "deepal_s7_ev",
    brand: "深蓝",
    model: "S7 EV",
    priceRange: [15.99, 19.99],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 520,
    realWorldRange: 416,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 7.5,
    memoryParking: 7.0,
    infotainmentScore: 7.5,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 7.0,
    suspensionScore: 7.0,
    rearSpace: 7.5,
    brandPremium: 5.5,
    serviceNetwork: 6.5,
    afterSalesScore: 6.5,
    resaleRate1Year: 0.74,
    resaleRate3Year: 0.56,
    resaleRate5Year: 0.42,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["3C超快充技术，30%-80%仅需约15分钟，补能效率在15-20万区间领先", "EPA1全电数字平台，天生后驱，操控灵动，AR-HUD标配", "零重力前排座椅+副驾屏，15万级车罕见高配体验"],
    risks: ["深蓝品牌知名度较低，二手保值率偏弱", "CLTC续航520km，实际续航约420km，冬季续航更短", "没有V2L放电功能，车外取电不支持"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "深蓝智驾 / 华为乾崑ADS SE（高配）",
    autoSummon: false,
    autoPark: 7.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "深蓝",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 120,
    charge10to80min: 15,
    hasHomeChargerIncluded: true,
    nvhScore: 6.5,
    sportinessScore: 7.0,
    zeroto100: 7.5,
    bodyLength: 4750,
    bodyWidth: 1930,
    bodyHeight: 1625,
    wheelbase: 2900,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "deepal_sl03_ev",
    brand: "深蓝",
    model: "SL03 EV",
    priceRange: [12.99, 14.69],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 530,
    realWorldRange: 424,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 6.5,
    cityNoa: 6.0,
    memoryParking: 6.0,
    infotainmentScore: 7.0,
    ecosystem: "自研",
    seatComfort: 7.0,
    soundInsulation: 6.5,
    suspensionScore: 7.0,
    rearSpace: 6.5,
    brandPremium: 5.0,
    serviceNetwork: 6.5,
    afterSalesScore: 6.5,
    resaleRate1Year: 0.72,
    resaleRate3Year: 0.54,
    resaleRate5Year: 0.4,
    special: {},
    highlights: ["3C超快充，30%-80%仅约15分钟，是同价位充电最快的轿车之一", "13万级轿车配备AR-HUD+14.6英寸屏，科技配置丰富超预期", "后驱+运动调校，驾驶乐趣在入门纯电轿车中突出"],
    risks: ["品牌溢价几乎为零，二手残值较低", "内饰用料与配置在同价位中处于中等水平", "与比亚迪秦EV/PLUS同价位竞争激烈，差异化不够明显"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "深蓝智驾 L2+",
    autoSummon: false,
    autoPark: 6.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "none",
    hasHeatedSeats: "front",
    hasMassageSeats: "none",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: false,
    hasV2L: false,
    audioBrand: "深蓝",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: false,
    hasDigitalKey: true,
    maxChargePower: 120,
    charge10to80min: 15,
    hasHomeChargerIncluded: true,
    nvhScore: 6.5,
    sportinessScore: 7.5,
    zeroto100: 6.4,
    bodyLength: 4820,
    bodyWidth: 1890,
    bodyHeight: 1480,
    wheelbase: 2900,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 问界 ====================
  {
    id: "aito_m9",
    brand: "问界",
    model: "M9",
    priceRange: [46.98, 56.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1474,
    realWorldRange: 1253,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 9.5,
    cityNoa: 9.5,
    memoryParking: 9.5,
    infotainmentScore: 9.5,
    ecosystem: "自研",
    seatComfort: 9.5,
    soundInsulation: 9.5,
    suspensionScore: 9.0,
    rearSpace: 9.0,
    brandPremium: 8.5,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.85,
    resaleRate3Year: 0.7,
    resaleRate5Year: 0.56,
    special: {
      erevAdvantage: "增程无续航焦虑",
      huaweiSmartDriving: true,
    },
    highlights: ["华为ADS 3.3+4颗激光雷达，城市/高速全场景NOA，智驾为国产旗舰最强梯队", "75英寸AR-HUD+32英寸后排巨幕+25扬声器华为音响，车内娱乐体验碾压同级", "空气悬架标配+CLTC综合续航1474km，豪华旗舰SUV综合实力第一梯队"],
    risks: ["问界品牌相对新，豪华感认可度低于BBA，对部分消费者吸引力有限", "车身巨大（5230mm/1999mm），城市停车、掉头困难", "增程版快充功率仅约100kW（EREV），纯电版快充为800V更快"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "华为ADS 3.3",
    autoSummon: true,
    autoPark: 9.5,
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "HUAWEI SOUND",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 100,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,
    nvhScore: 9.5,
    sportinessScore: 7.0,
    zeroto100: 4.9,
    bodyLength: 5230,
    bodyWidth: 1999,
    bodyHeight: 1800,
    wheelbase: 3110,
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 极氪 ====================
  {
    id: "zeekr_001",
    brand: "极氪",
    model: "001",
    priceRange: [25.9, 32.98],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 750,
    realWorldRange: 600,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 7.5,
    memoryParking: 7.5,
    infotainmentScore: 8.5,
    ecosystem: "自研",
    seatComfort: 9.0,
    soundInsulation: 8.5,
    suspensionScore: 7.5,
    rearSpace: 7.5,
    brandPremium: 8.0,
    serviceNetwork: 7.0,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.51,
    special: {},
    highlights: ["800V/900V超快充平台，最大充电功率500kW，10%-80%最快11分钟，补能效率行业顶尖", "Yamaha音响标配+AR-HUD+电动吸合门+前备厢（31L），豪华配置堆料感十足", "掀背轿跑造型，CLTC续航高达810km，兼顾颜值、空间与长途续航能力"],
    risks: ["车高仅1533-1545mm，后排乘客头部空间较紧，不适合身高较高的乘客", "品牌溢价相对特斯拉和BBA仍有差距，二手保值率低于同价位豪华品牌", "空气悬架需额外选配（28,000元），标配缺乏底盘调节灵活性"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "ZEEKR AD Orin-X×2",
    autoSummon: false,
    autoPark: 7.5,
    hasFrunk: true,
    hasRearScreen: true,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "Yamaha",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 500,
    charge10to80min: 11,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 9.0,
    zeroto100: 3.3,
    bodyLength: 4977,
    bodyWidth: 1999,
    bodyHeight: 1539,
    wheelbase: 3005,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "zeekr_007",
    brand: "极氪",
    model: "007",
    priceRange: [20.99, 29.99],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 688,
    realWorldRange: 550,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 7.5,
    memoryParking: 7.5,
    infotainmentScore: 8.0,
    ecosystem: "自研",
    seatComfort: 8.5,
    soundInsulation: 8.5,
    suspensionScore: 8.0,
    rearSpace: 8.0,
    brandPremium: 7.5,
    serviceNetwork: 7.0,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.51,
    special: {},
    highlights: ["800V超快充平台，最大500kW，10%-80%仅约11分钟，是同价位充电最快的轿车之一", "CLTC续航最长870km（长续航版），AR-HUD+无框车门+前排通风按摩，配置在20-30万轿车中出色", "轴距2928mm，后排空间宽敞，五连杆后悬架+后轮转向，驾驶操控与乘坐舒适兼顾"],
    risks: ["品牌服务网络覆盖不如比亚迪、特斯拉，三四线城市售后维保便利性有限", "内饰豪华感相对同价位竞品（如智界S7）略有差距，品牌溢价空间有限", "无前备厢设计，储物空间相比极氪001和小米SU7略显不足"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "ZEEKR AD Orin-X×2",
    autoSummon: false,
    autoPark: 7.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "极氪",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 500,
    charge10to80min: 11,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 8.5,
    zeroto100: 4.0,
    bodyLength: 4865,
    bodyWidth: 1900,
    bodyHeight: 1450,
    wheelbase: 2928,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "zeekr_7x",
    brand: "极氪",
    model: "7X",
    priceRange: [22.98, 26.98],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 780,
    realWorldRange: 624,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 7.5,
    memoryParking: 7.5,
    infotainmentScore: 8.0,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 8.0,
    suspensionScore: 7.5,
    rearSpace: 8.0,
    brandPremium: 7.5,
    serviceNetwork: 7.0,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.8,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.51,
    special: {},
    highlights: ["800V/900V超快充SUV，最大500kW，10%-80%最快11分钟，纯电SUV中补能速度顶尖", "前备厢（44-62L）+AR-HUD+可选气悬架，20-27万SUV的配置天花板之一", "CLTC续航高达802km（长续航RWD），家用通勤+长途出行均无里程焦虑"],
    risks: ["标配无气悬架（需额外加价20,000元选配），标配悬架舒适性不如同价位竞品", "极氪品牌服务网络相比比亚迪、问界仍有差距，尤其在低线城市", "车高1661mm，后排头部空间对高个乘客略显紧张，家用实用性稍逊"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "ZEEKR AD Orin-X×2 / Thor-U 700TOPS",
    autoSummon: false,
    autoPark: 7.5,
    hasFrunk: true,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "极氪",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 500,
    charge10to80min: 11,
    hasHomeChargerIncluded: true,
    nvhScore: 8.0,
    sportinessScore: 8.5,
    zeroto100: 4.2,
    bodyLength: 4825,
    bodyWidth: 1930,
    bodyHeight: 1661,
    wheelbase: 2925,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 小米 ====================
  {
    id: "xiaomi_su7",
    brand: "小米",
    model: "SU7",
    priceRange: [21.59, 29.99],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 800,
    realWorldRange: 640,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.5,
    cityNoa: 8.0,
    memoryParking: 8.0,
    infotainmentScore: 9.5,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 8.0,
    suspensionScore: 8.5,
    rearSpace: 8.0,
    brandPremium: 9.0,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.83,
    resaleRate3Year: 0.68,
    resaleRate5Year: 0.54,
    special: {},
    highlights: ["Max版0-100加速2.78秒，800V+500kW超快充，10%-80%最快19分钟，性能与补能能力俱佳", "小米生态深度融合，车机系统流畅度和互联性在国产新势力中名列前茅，MIUI车机生态无缝对接", "前备厢105L+电动吸合门全系标配+无框车门，配置堆料毫无保留，性价比极高"],
    risks: ["标配（SU7）为400V平台，入门版充电速度明显慢于竞品，需选Pro或Max才享受800V快充", "空气悬架仅Max版标配，其余版本不可选配，中低配底盘舒适性受限", "品牌认知度极高但小米汽车服务网络建设尚在扩张期，三四线城市售后便利性不如BYD"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "小米智驾 Orin-X×2",
    autoSummon: true,
    autoPark: 8.0,
    hasFrunk: true,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "小米",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 500,
    charge10to80min: 19,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 9.5,
    zeroto100: 2.78,
    bodyLength: 4997,
    bodyWidth: 1963,
    bodyHeight: 1440,
    wheelbase: 3000,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "xiaomi_yu7",
    brand: "小米",
    model: "YU7",
    priceRange: [25.35, 32.99],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 835,
    realWorldRange: 668,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.5,
    cityNoa: 8.0,
    memoryParking: 8.0,
    infotainmentScore: 9.5,
    ecosystem: "自研",
    seatComfort: 8.5,
    soundInsulation: 8.0,
    suspensionScore: 8.5,
    rearSpace: 8.5,
    brandPremium: 9.0,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.83,
    resaleRate3Year: 0.67,
    resaleRate5Year: 0.53,
    special: {},
    highlights: ["全系800V，标配CLTC续航835km（标准版），前备厢141L，纯电SUV中实用性顶尖", "NVIDIA Thor 700TOPS智驾平台+后排6.68寸触控屏+前后排通风座椅，高配豪华感极强", "小米生态无缝互联，Max版0-100加速3.23秒，兼顾家用舒适与性能驾驶"],
    risks: ["空气悬架仅Max版标配，标准版/Pro版无空悬，高速行驶质感与竞品问界M7/M9有差距", "上市时间晚（2025年6月），口碑与实际可靠性数据尚在积累中，长期稳定性未知", "小米汽车服务网络尚在建设，与比亚迪和传统车企相比售后便利性存在明显差距"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "小米智驾 NVIDIA Thor 700TOPS",
    autoSummon: true,
    autoPark: 8.0,
    hasFrunk: true,
    hasRearScreen: true,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "小米",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 300,
    charge10to80min: 20,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 9.0,
    zeroto100: 3.23,
    bodyLength: 4999,
    bodyWidth: 1996,
    bodyHeight: 1608,
    wheelbase: 3000,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 零跑 ====================
  {
    id: "leapmotor_c11",
    brand: "零跑",
    model: "C11",
    priceRange: [12.88, 20.58],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 640,
    realWorldRange: 512,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 6.5,
    memoryParking: 6.5,
    infotainmentScore: 7.0,
    ecosystem: "自研",
    seatComfort: 7.0,
    soundInsulation: 6.5,
    suspensionScore: 6.5,
    rearSpace: 7.5,
    brandPremium: 5.5,
    serviceNetwork: 6.5,
    afterSalesScore: 6.5,
    resaleRate1Year: 0.73,
    resaleRate3Year: 0.55,
    resaleRate5Year: 0.41,
    special: {},
    highlights: ["12.88万起的800V纯电SUV，CLTC续航640km，是同价位充电速度最快的选择之一", "无框车门+V2L放电3.3kW，高性价比配置在13-20万SUV中脱颖而出", "2026款全面升级，Orin-X智驾芯片支持高速NOA，L2+能力超越同价位大多数竞品"],
    risks: ["零跑品牌溢价低，二手保值率在国产新势力中偏弱，三年残值约55%", "内饰用料与做工精致度相比极氪、小米有明显差距，配件质感一般", "充电桩网络和服务网点密度不及蔚来、比亚迪，出远门使用第三方桩需注意"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "Leapmotor Pilot Orin-X",
    autoSummon: false,
    autoPark: 6.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "零跑",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 120,
    charge10to80min: 28,
    hasHomeChargerIncluded: true,
    nvhScore: 6.5,
    sportinessScore: 7.0,
    zeroto100: 6.1,
    bodyLength: 4780,
    bodyWidth: 1905,
    bodyHeight: 1675,
    wheelbase: 2930,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "leapmotor_c16",
    brand: "零跑",
    model: "C16",
    priceRange: [15.18, 18.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1095,
    realWorldRange: 930,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 6.5,
    memoryParking: 6.5,
    infotainmentScore: 7.0,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 6.5,
    suspensionScore: 6.5,
    rearSpace: 9.0,
    brandPremium: 5.5,
    serviceNetwork: 6.5,
    afterSalesScore: 6.5,
    resaleRate1Year: 0.72,
    resaleRate3Year: 0.54,
    resaleRate5Year: 0.4,
    special: {
      erevAdvantage: "增程无续航焦虑",
    },
    highlights: ["6座/5座灵活布局，增程版综合续航1095km，是家庭长途出行的高性价比之选", "15.18万起，中大型6座SUV中定价极低，后排空间媲美20-30万同级车型", "2026款搭载高通骁龙8650+Orin-X，激光雷达版支持城市/高速NOA，科技配置大幅升级"],
    risks: ["增程版DC快充功率约80kW，充电速度偏慢，快充30%-80%约需35分钟", "零跑品牌服务网络密度和品牌认知度低，二手保值率在国产新势力中处于低位", "车身高度达1770mm，风阻系数偏大，高速能耗相对较高"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "Leapmotor Pilot Qualcomm 8650",
    autoSummon: false,
    autoPark: 6.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "零跑",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 80,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,
    nvhScore: 6.5,
    sportinessScore: 6.0,
    zeroto100: 6.37,
    bodyLength: 4915,
    bodyWidth: 1905,
    bodyHeight: 1770,
    wheelbase: 2825,
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "leapmotor_c10",
    brand: "零跑",
    model: "C10",
    priceRange: [11.18, 16.88],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 605,
    realWorldRange: 484,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7.0,
    cityNoa: 6.0,
    memoryParking: 6.0,
    infotainmentScore: 7.0,
    ecosystem: "自研",
    seatComfort: 7.0,
    soundInsulation: 6.5,
    suspensionScore: 6.5,
    rearSpace: 7.0,
    brandPremium: 5.0,
    serviceNetwork: 6.5,
    afterSalesScore: 6.5,
    resaleRate1Year: 0.72,
    resaleRate3Year: 0.54,
    resaleRate5Year: 0.4,
    special: {},
    highlights: ["11.18万起的800V纯电紧凑型SUV，CLTC续航605km，同价位中续航与充电平台兼顾者少见", "V2L放电3.3kW标配，支持车外用电，在10-15万价位段属于罕见高配实用功能", "全系标配360环视+无线充电，基础科技配置超越同价位大多数竞品"],
    risks: ["DC快充功率仅80kW，实际充电速度不如标称800V带来的预期，30%-80%约需30分钟", "品牌弱势，零跑二手保值率偏低，5年残值约40%，投资回报率差", "智驾仅L2级别，与主流新势力L2+（城市NOA）存在明显差距"],
    adsLevel: "L2",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "Leapmotor Pilot OS",
    autoSummon: false,
    autoPark: 6.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "零跑",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 80,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,
    nvhScore: 6.5,
    sportinessScore: 6.5,
    zeroto100: 5.9,
    bodyLength: 4739,
    bodyWidth: 1900,
    bodyHeight: 1680,
    wheelbase: 2825,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 乐道 ====================
  {
    id: "ledao_l60",
    brand: "乐道",
    model: "L60",
    priceRange: [14.99, 25.59],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: true,
    cltcRange: 740,
    realWorldRange: 592,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7.5,
    cityNoa: 7.0,
    memoryParking: 7.0,
    infotainmentScore: 8.0,
    ecosystem: "自研",
    seatComfort: 8.0,
    soundInsulation: 7.5,
    suspensionScore: 7.5,
    rearSpace: 8.5,
    brandPremium: 6.5,
    serviceNetwork: 8.0,
    afterSalesScore: 8.0,
    resaleRate1Year: 0.76,
    resaleRate3Year: 0.6,
    resaleRate5Year: 0.46,
    special: {
      batteryRentalMonthly: [728, 1128],
      swapCoverage: 6,
    },
    highlights: ["支持蔚来换电网络，BaaS方案最低14.99万起，是同尺寸SUV中首付门槛最低的选择", "900V平台+CDC电磁悬架，无框车门+13寸HUD，NIO技术下放让15-25万段享受旗舰体验", "轴距2950mm后排空间宽裕，蔚来服务体系覆盖，家用舒适性与保障完善度双优"],
    risks: ["不换电时充电功率约150kW，补能速度不如极氪、小米等800V+竞品", "乐道品牌知名度弱于NIO本体，二手保值率尚待市场验证，预计低于蔚来主品牌", "换电依赖蔚来换电站网络，在非一二线城市覆盖不稳定，长途自驾换电体验不如充电灵活"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "蔚来NAD Orin-X",
    autoSummon: false,
    autoPark: 7.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "乐道",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 150,
    charge10to80min: 22,
    hasHomeChargerIncluded: true,
    nvhScore: 7.5,
    sportinessScore: 7.0,
    zeroto100: 4.6,
    bodyLength: 4828,
    bodyWidth: 1930,
    bodyHeight: 1616,
    wheelbase: 2950,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 智己 ====================
  {
    id: "zhiji_l7",
    brand: "智己",
    model: "L7",
    priceRange: [29.19, 41.99],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 660,
    realWorldRange: 528,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 7.5,
    memoryParking: 8.0,
    infotainmentScore: 8.0,
    ecosystem: "自研",
    seatComfort: 9.5,
    soundInsulation: 9.0,
    suspensionScore: 8.5,
    rearSpace: 9.5,
    brandPremium: 7.0,
    serviceNetwork: 6.5,
    afterSalesScore: 7.0,
    resaleRate1Year: 0.76,
    resaleRate3Year: 0.6,
    resaleRate5Year: 0.46,
    special: {},
    highlights: ["轴距3100mm，同级最长，后排豪华感堪比BBA行政轿车，前后排通风按摩座椅全系标配", "NVH静谧性出色，电动吸合门+后排电动遮阳帘，乘坐豪华体验在国产轿车中首屈一指", "V2L放电6.6kW，车外大功率用电能力为同类产品最强，适合商务用途和野外露营"],
    risks: ["不支持800V超快充，最大DC充电功率约120kW，充电速度在30-40万价位段明显落后", "智己品牌认知度和溢价相比BBA差距明显，二手保值率预计偏低", "车身超长（5108mm），城市停车和掉头极为不便，不适合频繁城区驾驶"],
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "IM AD Orin-X 254TOPS",
    autoSummon: false,
    autoPark: 8.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "智己",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 120,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,
    nvhScore: 9.0,
    sportinessScore: 8.0,
    zeroto100: 3.87,
    bodyLength: 5108,
    bodyWidth: 1960,
    bodyHeight: 1485,
    wheelbase: 3100,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },
  {
    id: "zhiji_ls6",
    brand: "智己",
    model: "LS6",
    priceRange: [19.79, 28.49],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1300,
    realWorldRange: 1105,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 8.0,
    cityNoa: 8.0,
    memoryParking: 8.0,
    infotainmentScore: 8.5,
    ecosystem: "自研",
    seatComfort: 8.5,
    soundInsulation: 8.0,
    suspensionScore: 8.5,
    rearSpace: 8.5,
    brandPremium: 7.5,
    serviceNetwork: 6.5,
    afterSalesScore: 7.0,
    resaleRate1Year: 0.77,
    resaleRate3Year: 0.61,
    resaleRate5Year: 0.47,
    special: {
      erevAdvantage: "增程无续航焦虑",
    },
    highlights: ["2026款增程版综合续航突破1300km（CLTC），城市零排放+长途无焦虑，家用覆盖最全面", "800V纯电版10%-80%最快17分钟，增程版亦支持快充，补能灵活性行业领先", "无框车门+前后排通风座椅+V2L 6kW，20-28万SUV中豪华配置与实用功能同类最强"],
    risks: ["增程版部分配置无空气悬架，底盘豪华感相比问界M7、腾势N7略有差距", "智己品牌服务网络规模偏小，三四线城市维保便利性不如比亚迪和大众", "车宽1988mm，在狭窄城市道路停车和通行时略显局促，新手驾驶压力较大"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "IM AD Orin-X 254TOPS",
    autoSummon: true,
    autoPark: 8.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "智己",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 130,
    charge10to80min: 17,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 8.0,
    zeroto100: 4.0,
    bodyLength: 4937,
    bodyWidth: 1988,
    bodyHeight: 1672,
    wheelbase: 2960,
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 智界 ====================
  {
    id: "zhijie_s7",
    brand: "智界",
    model: "S7",
    priceRange: [22.98, 32.98],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 800,
    realWorldRange: 640,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 9.0,
    cityNoa: 9.0,
    memoryParking: 9.0,
    infotainmentScore: 9.5,
    ecosystem: "自研",
    seatComfort: 8.5,
    soundInsulation: 8.5,
    suspensionScore: 8.5,
    rearSpace: 8.5,
    brandPremium: 8.5,
    serviceNetwork: 7.5,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.67,
    resaleRate5Year: 0.53,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为乾崑ADS 4全场景智驾，高速/城市/泊车NOA全覆盖，智驾能力在国产轿车中属第一梯队", "HUAWEI SOUND音响+鸿蒙车机+CLTC续航最长855km，华为生态体验无缝融合，科技感极强", "800V+215kW快充，无框门+V2L 6kW，在23-33万轿车段配置完整度与科技上限均处领先"],
    risks: ["标配版无空气悬架，2026款Max/Max+才标配气悬，中低配底盘调节能力受限", "智界品牌独立性较低，深度绑定华为，品牌溢价可能随华为战略变化而波动", "充电功率215kW，不如极氪007/001（500kW）和小米SU7 Max（500kW），补能竞争力相对弱"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "华为乾崑ADS 4",
    autoSummon: true,
    autoPark: 9.0,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "HUAWEI SOUND",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 215,
    charge10to80min: 22,
    hasHomeChargerIncluded: true,
    nvhScore: 8.5,
    sportinessScore: 8.5,
    zeroto100: 3.3,
    bodyLength: 4971,
    bodyWidth: 1963,
    bodyHeight: 1467,
    wheelbase: 2950,
    platePolicy: {
      beijing: "green_plate",
      shanghai: "free_green",
      shenzhen: "green_plate",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },

  // ==================== 岚图 ====================
  {
    id: "voyah_free",
    brand: "岚图",
    model: "FREE",
    priceRange: [21.99, 27.99],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1357,
    realWorldRange: 1154,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8.5,
    cityNoa: 8.5,
    memoryParking: 8.5,
    infotainmentScore: 9.0,
    ecosystem: "自研",
    seatComfort: 8.5,
    soundInsulation: 8.0,
    suspensionScore: 8.5,
    rearSpace: 8.5,
    brandPremium: 7.5,
    serviceNetwork: 7.0,
    afterSalesScore: 7.5,
    resaleRate1Year: 0.78,
    resaleRate3Year: 0.63,
    resaleRate5Year: 0.49,
    special: {
      erevAdvantage: "增程无续航焦虑",
      huaweiSmartDriving: true,
    },
    highlights: ["华为乾崑ADS 4（FREE+款）全场景智驾，城市NOA能力在25万内SUV中居于顶尖行列", "Dynaudio丹拿音响+空气悬架+前后通风按摩座椅，增程SUV中豪华配置兼顾实用性", "CLTC增程综合续航1357km，纯电318km城市日常无需燃油，长途一加油解决里程焦虑"],
    risks: ["增程车型DC快充功率140kW，纯电模式充电速度不及极氪、小米等800V竞品", "岚图品牌定位较高端，服务网络规模不及比亚迪，三四线城市维保便利性有限", "车重较大，增程版能耗相对纯电车高，市区拥堵时燃油机启动音振对NVH有一定影响"],
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "华为乾崑ADS 4 / 阿波罗2.0",
    autoSummon: true,
    autoPark: 8.5,
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "Dynaudio",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,
    maxChargePower: 140,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,
    nvhScore: 8.0,
    sportinessScore: 7.5,
    zeroto100: 4.9,
    bodyLength: 4915,
    bodyWidth: 1960,
    bodyHeight: 1645,
    wheelbase: 2960,
    platePolicy: {
      beijing: "restricted",
      shanghai: "bid_plate",
      shenzhen: "restricted",
      guangzhou: "green_plate",
      hangzhou: "green_plate",
      chengdu: "green_plate",
    },
  },


];
