/**
 * 车型知识库 — 硬编码典型数据
 * ===========================================
 * 修改说明：直接编辑本文件中的 carDatabase 数组即可新增/修改车型。
 * 每个字段含义参见 shared/schema.ts 中的 CarModel 接口。
 * 评分类字段统一使用 0-10 分制，保值率使用 0-1 小数。
 */

import type { CarModel } from "../shared/schema";

export const carDatabase: CarModel[] = [
  // ==================== 理想 ====================
  {
    id: "lixiang_l7",
    brand: "理想",
    model: "L7",
    priceRange: [31.98, 37.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "理想自研",
    seatComfort: 9,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 7,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.65,
    resaleRate5Year: 0.48,
    special: {
      erevAdvantage: "增程无续航焦虑，长途自驾无忧",
      futureBevPlan: true,
    },
    highlights: ["增程无焦虑", "家庭旗舰舒适", "冰箱彩电大沙发"],
    risks: ["纯电续航较短", "增程技术路线未来不确定性"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max/Pro",
    autoSummon: false,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 5,
    zeroto100: 5.3,
  },
  {
    id: "lixiang_l8",
    brand: "理想",
    model: "L8",
    priceRange: [33.98, 39.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "理想自研",
    seatComfort: 9,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 9,
    brandPremium: 7,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.82,
    resaleRate3Year: 0.64,
    resaleRate5Year: 0.46,
    special: {
      erevAdvantage: "六座大空间，增程长途无焦虑",
      futureBevPlan: true,
    },
    highlights: ["六座大空间", "增程无焦虑", "家庭首选"],
    risks: ["价格偏高", "增程路线长期不确定"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max/Pro",
    autoSummon: false,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 5,
    zeroto100: 5.3,
  },
  {
    id: "lixiang_l9",
    brand: "理想",
    model: "L9",
    priceRange: [42.98, 45.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1315,
    realWorldRange: 1100,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 7,
    memoryParking: 8,
    infotainmentScore: 9,
    ecosystem: "理想自研",
    seatComfort: 10,
    soundInsulation: 9,
    suspensionScore: 9,
    rearSpace: 10,
    brandPremium: 8,
    serviceNetwork: 7,
    afterSalesScore: 8,
    resaleRate1Year: 0.83,
    resaleRate3Year: 0.66,
    resaleRate5Year: 0.49,
    special: {
      erevAdvantage: "旗舰全尺寸SUV，增程长途无焦虑",
      futureBevPlan: true,
    },
    highlights: ["全尺寸旗舰", "极致舒适", "智驾能力强"],
    risks: ["价格最高", "尺寸过大停车不便"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "AD Max",
    autoSummon: false,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front_rear",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 150,
    charge10to80min: 35,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 9,
    sportinessScore: 4,
    zeroto100: 5.3,
  },

  // ==================== 蔚来 ====================
  {
    id: "nio_es6",
    brand: "蔚来",
    model: "ES6",
    priceRange: [33.80, 39.60],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: true,
    cltcRange: 625,
    realWorldRange: 490,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 8,
    highwayNoa: 7,
    cityNoa: 5,
    memoryParking: 6,
    infotainmentScore: 7,
    ecosystem: "蔚来自研",
    seatComfort: 8,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 8,
    serviceNetwork: 9,
    afterSalesScore: 9,
    resaleRate1Year: 0.78,
    resaleRate3Year: 0.58,
    resaleRate5Year: 0.40,
    special: {
      batteryRentalMonthly: [728, 1128],
      swapCoverage: 8,
    },
    highlights: ["换电3分钟满电", "车电分离降低购车成本", "服务体验行业标杆"],
    risks: ["纯电续航焦虑", "换电站覆盖三四线不足", "车电分离合同复杂"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsIncludedYears: 5,
    adsPlatform: "NAD",
    autoSummon: true,
    autoPark: 7,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: true,
    hasAirSuspension: true,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "杜比全景声7.1.4",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 180,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 6,
    zeroto100: 4.5,
  },
  {
    id: "nio_et5",
    brand: "蔚来",
    model: "ET5",
    priceRange: [29.80, 35.60],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: true,
    cltcRange: 560,
    realWorldRange: 430,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 8,
    highwayNoa: 7,
    cityNoa: 5,
    memoryParking: 6,
    infotainmentScore: 7,
    ecosystem: "蔚来自研",
    seatComfort: 7,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 6,
    brandPremium: 7,
    serviceNetwork: 9,
    afterSalesScore: 9,
    resaleRate1Year: 0.76,
    resaleRate3Year: 0.55,
    resaleRate5Year: 0.38,
    special: {
      batteryRentalMonthly: [728, 1128],
      swapCoverage: 8,
    },
    highlights: ["换电便捷", "运动轿车造型", "服务好"],
    risks: ["纯电续航一般", "后排空间不大", "保值率偏低"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsIncludedYears: 5,
    adsPlatform: "NAD",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: true,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: true,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: true,
    audioBrand: "杜比全景声7.1.4",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 180,
    charge10to80min: 30,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 7,
    zeroto100: 4.0,
  },

  // ==================== 小鹏 ====================
  {
    id: "xpeng_g6",
    brand: "小鹏",
    model: "G6",
    priceRange: [20.99, 27.69],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 580,
    realWorldRange: 450,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 9,
    cityNoa: 9,
    memoryParking: 8,
    infotainmentScore: 7,
    ecosystem: "小鹏自研(安卓)",
    seatComfort: 7,
    soundInsulation: 6,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 5,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.73,
    resaleRate3Year: 0.50,
    resaleRate5Year: 0.33,
    special: {},
    highlights: ["800V超充架构", "城市NOA行业领先", "性价比高"],
    risks: ["品牌溢价低保值率差", "做工细节一般", "服务网络偏弱"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "free",
    adsCostUpfront: 0,
    adsPlatform: "XNGP MAX",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 400,
    charge10to80min: 20,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 7,
    zeroto100: 3.9,
  },
  {
    id: "xpeng_g9",
    brand: "小鹏",
    model: "G9",
    priceRange: [26.39, 35.99],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 650,
    realWorldRange: 510,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 9,
    cityNoa: 9,
    memoryParking: 8,
    infotainmentScore: 8,
    ecosystem: "小鹏自研(安卓)",
    seatComfort: 8,
    soundInsulation: 7,
    suspensionScore: 8,
    rearSpace: 8,
    brandPremium: 5,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.74,
    resaleRate3Year: 0.52,
    resaleRate5Year: 0.35,
    special: {},
    highlights: ["800V超充", "智驾旗舰", "空间表现好"],
    risks: ["保值率一般", "品牌力待提升", "售后覆盖不足"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "upfront",
    adsCostUpfront: 2.0,
    adsPlatform: "Ultra VLA",
    autoSummon: true,
    autoPark: 9,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front_rear",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "丹拿",
    hasFramelessDoor: false,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 430,
    charge10to80min: 18,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 7,
    zeroto100: 3.9,
  },

  // ==================== 特斯拉 ====================
  {
    id: "tesla_model3",
    brand: "特斯拉",
    model: "Model 3",
    priceRange: [23.19, 33.19],
    bodyType: "sedan",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 606,
    realWorldRange: 480,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 5,
    infotainmentScore: 7,
    ecosystem: "特斯拉封闭生态",
    seatComfort: 6,
    soundInsulation: 6,
    suspensionScore: 6,
    rearSpace: 6,
    brandPremium: 9,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.86,
    resaleRate3Year: 0.70,
    resaleRate5Year: 0.52,
    special: {},
    highlights: ["保值率行业第一", "超充网络成熟", "全球品牌影响力"],
    risks: ["内饰简陋", "舒适性一般", "智驾在国内受限"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "upfront",
    adsCostUpfront: 6.4,
    adsPlatform: "FSD V13",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: true,
    frunkVolume: 88,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "none",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "自研",
    hasFramelessDoor: true,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 250,
    charge10to80min: 25,
    hasHomeChargerIncluded: false,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 8,
    zeroto100: 3.1,
  },
  {
    id: "tesla_modely",
    brand: "特斯拉",
    model: "Model Y",
    priceRange: [24.99, 35.49],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 554,
    realWorldRange: 430,
    supportsFastCharge: true,
    supportsUltraCharge: true,
    swapNetworkMaturity: 0,
    highwayNoa: 7,
    cityNoa: 6,
    memoryParking: 5,
    infotainmentScore: 7,
    ecosystem: "特斯拉封闭生态",
    seatComfort: 6,
    soundInsulation: 6,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 9,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.87,
    resaleRate3Year: 0.72,
    resaleRate5Year: 0.54,
    special: {},
    highlights: ["保值率极高", "SUV实用性好", "超充覆盖广"],
    risks: ["内饰简陋", "舒适性不如同价位国产", "FSD在国内受限"],

    // 智驾费用
    adsLevel: "L2+",
    adsCostMode: "upfront",
    adsCostUpfront: 6.4,
    adsPlatform: "FSD V13",
    autoSummon: true,
    autoPark: 6,

    // 配置
    hasFrunk: true,
    frunkVolume: 117,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "none",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "none",
    hasHud: false,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "自研",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 250,
    charge10to80min: 28,
    hasHomeChargerIncluded: false,

    // NVH与驾驶
    nvhScore: 6,
    sportinessScore: 7,
    zeroto100: 3.7,
  },

  // ==================== 问界 ====================
  {
    id: "aito_m5",
    brand: "问界",
    model: "M5",
    priceRange: [24.98, 27.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1265,
    realWorldRange: 1050,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 8,
    memoryParking: 7,
    infotainmentScore: 9,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 7,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 7,
    brandPremium: 7,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.80,
    resaleRate3Year: 0.62,
    resaleRate5Year: 0.44,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾ADS", "鸿蒙座舱体验一流", "增程无焦虑"],
    risks: ["底盘调校一般", "品牌认知仍在建设", "与华为绑定过深"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 Max",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "华为SOUND",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 100,
    charge10to80min: 40,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 5,
    zeroto100: 4.4,
  },
  {
    id: "aito_m7",
    brand: "问界",
    model: "M7",
    priceRange: [24.98, 32.98],
    bodyType: "suv",
    powerType: "erev",
    canSwapBattery: false,
    cltcRange: 1300,
    realWorldRange: 1080,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 8,
    memoryParking: 8,
    infotainmentScore: 9,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 8,
    soundInsulation: 7,
    suspensionScore: 7,
    rearSpace: 9,
    brandPremium: 7,
    serviceNetwork: 8,
    afterSalesScore: 7,
    resaleRate1Year: 0.81,
    resaleRate3Year: 0.63,
    resaleRate5Year: 0.45,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾旗舰", "六座大空间", "鸿蒙座舱"],
    risks: ["底盘质感弱于理想", "品牌独立性存疑", "赛力斯品控口碑一般"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 Max",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: true,
    hasRearSunshade: false,
    hasAirSuspension: false,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "华为SOUND",
    hasFramelessDoor: false,
    hasPowerDoor: false,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 100,
    charge10to80min: 40,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 7,
    sportinessScore: 5,
    zeroto100: 4.8,
  },

  // ==================== 阿维塔 ====================
  {
    id: "avatr_11",
    brand: "阿维塔",
    model: "11",
    priceRange: [30.00, 39.00],
    bodyType: "suv",
    powerType: "bev",
    canSwapBattery: false,
    cltcRange: 600,
    realWorldRange: 470,
    supportsFastCharge: true,
    supportsUltraCharge: false,
    swapNetworkMaturity: 0,
    highwayNoa: 8,
    cityNoa: 7,
    memoryParking: 7,
    infotainmentScore: 8,
    ecosystem: "华为鸿蒙座舱",
    seatComfort: 8,
    soundInsulation: 8,
    suspensionScore: 8,
    rearSpace: 7,
    brandPremium: 6,
    serviceNetwork: 6,
    afterSalesScore: 6,
    resaleRate1Year: 0.74,
    resaleRate3Year: 0.52,
    resaleRate5Year: 0.35,
    special: {
      huaweiSmartDriving: true,
    },
    highlights: ["华为智驾加持", "高端运动定位", "长安+华为+宁德联合"],
    risks: ["品牌知名度低", "保值率不确定", "服务网络待完善"],

    // 智驾费用
    adsLevel: "L2++",
    adsCostMode: "both",
    adsCostUpfront: 3.6,
    adsCostMonthly: 720,
    adsCostYearly: 7200,
    adsPlatform: "ADS 3.0 (华为)",
    autoSummon: true,
    autoPark: 8,

    // 配置
    hasFrunk: false,
    hasRearScreen: false,
    hasRearSunshade: false,
    hasAirSuspension: true,
    hasVentilatedSeats: "front",
    hasHeatedSeats: "front_rear",
    hasMassageSeats: "front",
    hasHud: true,
    hasPhysicalButtons: false,
    hasWirelessCharge: true,
    hasElectricTailgate: true,
    hasV2L: false,
    audioBrand: "哈曼卡顿",
    hasFramelessDoor: true,
    hasPowerDoor: true,
    has360Camera: true,
    hasDigitalKey: true,

    // 补能
    maxChargePower: 240,
    charge10to80min: 25,
    hasHomeChargerIncluded: true,

    // NVH与驾驶
    nvhScore: 8,
    sportinessScore: 8,
    zeroto100: 3.98,
  },
];
